require('plugins')

require('utils.map')

require('general')
require('lsp')
require('_completion')
require('_treesitter')

require('_better_whitespace')
require('_bufferline')
require('_colorizer')
require('_gitsigns')
require('_goyo')
require('_illuminate')
require('_limelight')
require('_nvim-tree')
require('_qf')
require('_quick-scope')
require('_sneak')
require('_snippets')
require('_startify')
require('_statusline')
require('_telescope')
require('_toggleterm')
require('_vimwiki')
require('_which-key')
require('fzf')
